[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="VT323-Regular"
FontFile="VT323-Regular.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Midnight Bloom"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/2b-midnight-bloom.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#E91E63"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#FFFFFF"
AccentGlowColor="#FFFFFF"

HeaderTextColor="#FFFFFF"
DateTextColor="#FFFFFF"
TimeTextColor="#FFFFFF"

FormBackgroundColor="#E91E63"
BackgroundColor="#E91E63"

LoginFieldBackgroundColor="#5C5C5C"
PasswordFieldBackgroundColor="#5C5C5C"
LoginFieldTextColor="#121212"
PasswordFieldTextColor="#121212"
UserIconColor="#FFFFFF"
PasswordIconColor="#FFFFFF"

PlaceholderTextColor="#12121280"
WarningColor="#ff3333"

LoginButtonTextColor="#E91E63"
LoginButtonBackgroundColor="#FFFFFF"
SystemButtonsIconsColor="#FFFFFF"
SessionButtonTextColor="#FFFFFF"
VirtualKeyboardButtonTextColor="#FFFFFF"

DropdownTextColor="#121212"
DropdownSelectedBackgroundColor="#5C5C5Cbf"
DropdownBackgroundColor="#5C5C5C"

HighlightTextColor="#E91E63"
HighlightBackgroundColor="#5C5C5Cbf"
HighlightBorderColor="#FFFFFF"

HoverUserIconColor="#121212"
HoverPasswordIconColor="#121212"
HoverSystemButtonsIconsColor="#121212"
HoverSessionButtonTextColor="#121212"
HoverVirtualKeyboardButtonTextColor="#121212"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
