[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Roboto Mono"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Midnight Bloom"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/2b-midnight-bloom.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#0a0a1a"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#6677ff"
AccentGlowColor="#6677ff"

HeaderTextColor="#6677ff"
DateTextColor="#6677ff"
TimeTextColor="#6677ff"

FormBackgroundColor="#0a0a1a"
BackgroundColor="#0a0a1a"

LoginFieldBackgroundColor="#151530"
PasswordFieldBackgroundColor="#151530"
LoginFieldTextColor="#ccd5ff"
PasswordFieldTextColor="#ccd5ff"
UserIconColor="#6677ff"
PasswordIconColor="#6677ff"

PlaceholderTextColor="#ccd5ff80"
WarningColor="#ff3333"

LoginButtonTextColor="#0a0a1a"
LoginButtonBackgroundColor="#6677ff"
SystemButtonsIconsColor="#6677ff"
SessionButtonTextColor="#6677ff"
VirtualKeyboardButtonTextColor="#6677ff"

DropdownTextColor="#ccd5ff"
DropdownSelectedBackgroundColor="#151530bf"
DropdownBackgroundColor="#151530"

HighlightTextColor="#0a0a1a"
HighlightBackgroundColor="#151530bf"
HighlightBorderColor="#6677ff"

HoverUserIconColor="#ccd5ff"
HoverPasswordIconColor="#ccd5ff"
HoverSystemButtonsIconsColor="#ccd5ff"
HoverSessionButtonTextColor="#ccd5ff"
HoverVirtualKeyboardButtonTextColor="#ccd5ff"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
