[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="PixelOperator8"
FontFile="PixelOperator8.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Autumn Cat"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/autumn-cat.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#3E2723"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#E38D2D"
AccentGlowColor="#E38D2D"

HeaderTextColor="#E38D2D"
DateTextColor="#E38D2D"
TimeTextColor="#E38D2D"

FormBackgroundColor="#3E2723"
BackgroundColor="#3E2723"

LoginFieldBackgroundColor="#8D4B27"
PasswordFieldBackgroundColor="#8D4B27"
LoginFieldTextColor="#F5E6CC"
PasswordFieldTextColor="#F5E6CC"
UserIconColor="#E38D2D"
PasswordIconColor="#E38D2D"

PlaceholderTextColor="#F5E6CC80"
WarningColor="#ff3333"

LoginButtonTextColor="#3E2723"
LoginButtonBackgroundColor="#E38D2D"
SystemButtonsIconsColor="#E38D2D"
SessionButtonTextColor="#E38D2D"
VirtualKeyboardButtonTextColor="#E38D2D"

DropdownTextColor="#F5E6CC"
DropdownSelectedBackgroundColor="#8D4B27bf"
DropdownBackgroundColor="#8D4B27"

HighlightTextColor="#3E2723"
HighlightBackgroundColor="#8D4B27bf"
HighlightBorderColor="#E38D2D"

HoverUserIconColor="#F5E6CC"
HoverPasswordIconColor="#F5E6CC"
HoverSystemButtonsIconsColor="#F5E6CC"
HoverSessionButtonTextColor="#F5E6CC"
HoverVirtualKeyboardButtonTextColor="#F5E6CC"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
