[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Pixel Operator"
FontFile="PixelOperator.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Autumn Cat"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/autumn-cat.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#1a1005"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#ffa500"
AccentGlowColor="#ffa500"

HeaderTextColor="#ffa500"
DateTextColor="#ffa500"
TimeTextColor="#ffa500"

FormBackgroundColor="#1a1005"
BackgroundColor="#1a1005"

LoginFieldBackgroundColor="#332010"
PasswordFieldBackgroundColor="#332010"
LoginFieldTextColor="#ffe6cc"
PasswordFieldTextColor="#ffe6cc"
UserIconColor="#ffa500"
PasswordIconColor="#ffa500"

PlaceholderTextColor="#ffe6cc80"
WarningColor="#ff3333"

LoginButtonTextColor="#1a1005"
LoginButtonBackgroundColor="#ffa500"
SystemButtonsIconsColor="#ffa500"
SessionButtonTextColor="#ffa500"
VirtualKeyboardButtonTextColor="#ffa500"

DropdownTextColor="#ffe6cc"
DropdownSelectedBackgroundColor="#332010bf"
DropdownBackgroundColor="#332010"

HighlightTextColor="#1a1005"
HighlightBackgroundColor="#332010bf"
HighlightBorderColor="#ffa500"

HoverUserIconColor="#ffe6cc"
HoverPasswordIconColor="#ffe6cc"
HoverSystemButtonsIconsColor="#ffe6cc"
HoverSessionButtonTextColor="#ffe6cc"
HoverVirtualKeyboardButtonTextColor="#ffe6cc"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
