[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="PressStart2P-Regular"
FontFile="PressStart2P-Regular.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Before The Road"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/before-the-road.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#2D2B52"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#F08E33"
AccentGlowColor="#F08E33"

HeaderTextColor="#F08E33"
DateTextColor="#F08E33"
TimeTextColor="#F08E33"

FormBackgroundColor="#2D2B52"
BackgroundColor="#2D2B52"

LoginFieldBackgroundColor="#1A1A1A"
PasswordFieldBackgroundColor="#1A1A1A"
LoginFieldTextColor="#FFD1A4"
PasswordFieldTextColor="#FFD1A4"
UserIconColor="#F08E33"
PasswordIconColor="#F08E33"

PlaceholderTextColor="#FFD1A480"
WarningColor="#ff3333"

LoginButtonTextColor="#2D2B52"
LoginButtonBackgroundColor="#F08E33"
SystemButtonsIconsColor="#F08E33"
SessionButtonTextColor="#F08E33"
VirtualKeyboardButtonTextColor="#F08E33"

DropdownTextColor="#FFD1A4"
DropdownSelectedBackgroundColor="#1A1A1Abf"
DropdownBackgroundColor="#1A1A1A"

HighlightTextColor="#2D2B52"
HighlightBackgroundColor="#1A1A1Abf"
HighlightBorderColor="#F08E33"

HoverUserIconColor="#FFD1A4"
HoverPasswordIconColor="#FFD1A4"
HoverSystemButtonsIconsColor="#FFD1A4"
HoverSessionButtonTextColor="#FFD1A4"
HoverVirtualKeyboardButtonTextColor="#FFD1A4"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="right"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
