[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Pixel Operator"
FontFile="PixelOperator.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Dragon Bride"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/dragon-bride.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#1a0505"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#ff3333"
AccentGlowColor="#ff3333"

HeaderTextColor="#ff3333"
DateTextColor="#ff3333"
TimeTextColor="#ff3333"

FormBackgroundColor="#1a0505"
BackgroundColor="#1a0505"

LoginFieldBackgroundColor="#330a0a"
PasswordFieldBackgroundColor="#330a0a"
LoginFieldTextColor="#ffcccc"
PasswordFieldTextColor="#ffcccc"
UserIconColor="#ff3333"
PasswordIconColor="#ff3333"

PlaceholderTextColor="#ffcccc80"
WarningColor="#ff3333"

LoginButtonTextColor="#1a0505"
LoginButtonBackgroundColor="#ff3333"
SystemButtonsIconsColor="#ff3333"
SessionButtonTextColor="#ff3333"
VirtualKeyboardButtonTextColor="#ff3333"

DropdownTextColor="#ffcccc"
DropdownSelectedBackgroundColor="#330a0abf"
DropdownBackgroundColor="#330a0a"

HighlightTextColor="#1a0505"
HighlightBackgroundColor="#330a0abf"
HighlightBorderColor="#ff3333"

HoverUserIconColor="#ffcccc"
HoverPasswordIconColor="#ffcccc"
HoverSystemButtonsIconsColor="#ffcccc"
HoverSessionButtonTextColor="#ffcccc"
HoverVirtualKeyboardButtonTextColor="#ffcccc"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
