[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Silkscreen-Regular"
FontFile="Silkscreen-Regular.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Green Fields"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/green-fields-and-peaks.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#2E4057"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#4B713A"
AccentGlowColor="#4B713A"

HeaderTextColor="#4B713A"
DateTextColor="#4B713A"
TimeTextColor="#4B713A"

FormBackgroundColor="#2E4057"
BackgroundColor="#2E4057"

LoginFieldBackgroundColor="#8DBF72"
PasswordFieldBackgroundColor="#8DBF72"
LoginFieldTextColor="#F0F4F8"
PasswordFieldTextColor="#F0F4F8"
UserIconColor="#4B713A"
PasswordIconColor="#4B713A"

PlaceholderTextColor="#F0F4F880"
WarningColor="#ff3333"

LoginButtonTextColor="#2E4057"
LoginButtonBackgroundColor="#4B713A"
SystemButtonsIconsColor="#4B713A"
SessionButtonTextColor="#4B713A"
VirtualKeyboardButtonTextColor="#4B713A"

DropdownTextColor="#F0F4F8"
DropdownSelectedBackgroundColor="#8DBF72bf"
DropdownBackgroundColor="#8DBF72"

HighlightTextColor="#2E4057"
HighlightBackgroundColor="#8DBF72bf"
HighlightBorderColor="#4B713A"

HoverUserIconColor="#F0F4F8"
HoverPasswordIconColor="#F0F4F8"
HoverSystemButtonsIconsColor="#F0F4F8"
HoverSessionButtonTextColor="#F0F4F8"
HoverVirtualKeyboardButtonTextColor="#F0F4F8"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
