[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Goatskin Brush"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Green Fields"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/green-fields-and-peaks.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#0a1a0a"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#66ff66"
AccentGlowColor="#66ff66"

HeaderTextColor="#66ff66"
DateTextColor="#66ff66"
TimeTextColor="#66ff66"

FormBackgroundColor="#0a1a0a"
BackgroundColor="#0a1a0a"

LoginFieldBackgroundColor="#143314"
PasswordFieldBackgroundColor="#143314"
LoginFieldTextColor="#d6ffd6"
PasswordFieldTextColor="#d6ffd6"
UserIconColor="#66ff66"
PasswordIconColor="#66ff66"

PlaceholderTextColor="#d6ffd680"
WarningColor="#ff3333"

LoginButtonTextColor="#0a1a0a"
LoginButtonBackgroundColor="#66ff66"
SystemButtonsIconsColor="#66ff66"
SessionButtonTextColor="#66ff66"
VirtualKeyboardButtonTextColor="#66ff66"

DropdownTextColor="#d6ffd6"
DropdownSelectedBackgroundColor="#143314bf"
DropdownBackgroundColor="#143314"

HighlightTextColor="#0a1a0a"
HighlightBackgroundColor="#143314bf"
HighlightBorderColor="#66ff66"

HoverUserIconColor="#d6ffd6"
HoverPasswordIconColor="#d6ffd6"
HoverSystemButtonsIconsColor="#d6ffd6"
HoverSessionButtonTextColor="#d6ffd6"
HoverVirtualKeyboardButtonTextColor="#d6ffd6"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
