[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Merriweather"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Sea Ships"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/landscape-sea-ships.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#05151a"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#33ccff"
AccentGlowColor="#33ccff"

HeaderTextColor="#33ccff"
DateTextColor="#33ccff"
TimeTextColor="#33ccff"

FormBackgroundColor="#05151a"
BackgroundColor="#05151a"

LoginFieldBackgroundColor="#0a2a33"
PasswordFieldBackgroundColor="#0a2a33"
LoginFieldTextColor="#ccf5ff"
PasswordFieldTextColor="#ccf5ff"
UserIconColor="#33ccff"
PasswordIconColor="#33ccff"

PlaceholderTextColor="#ccf5ff80"
WarningColor="#ff3333"

LoginButtonTextColor="#05151a"
LoginButtonBackgroundColor="#33ccff"
SystemButtonsIconsColor="#33ccff"
SessionButtonTextColor="#33ccff"
VirtualKeyboardButtonTextColor="#33ccff"

DropdownTextColor="#ccf5ff"
DropdownSelectedBackgroundColor="#0a2a33bf"
DropdownBackgroundColor="#0a2a33"

HighlightTextColor="#05151a"
HighlightBackgroundColor="#0a2a33bf"
HighlightBorderColor="#33ccff"

HoverUserIconColor="#ccf5ff"
HoverPasswordIconColor="#ccf5ff"
HoverSystemButtonsIconsColor="#ccf5ff"
HoverSessionButtonTextColor="#ccf5ff"
HoverVirtualKeyboardButtonTextColor="#ccf5ff"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
