[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="VT323-Regular"
FontFile="VT323-Regular.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Motorcycle Chaos"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/motorcycle-girl-chaos.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#1A1C1E"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#A61C28"
AccentGlowColor="#A61C28"

HeaderTextColor="#A61C28"
DateTextColor="#A61C28"
TimeTextColor="#A61C28"

FormBackgroundColor="#1A1C1E"
BackgroundColor="#1A1C1E"

LoginFieldBackgroundColor="#EAEAEA"
PasswordFieldBackgroundColor="#EAEAEA"
LoginFieldTextColor="#8A98A5"
PasswordFieldTextColor="#8A98A5"
UserIconColor="#A61C28"
PasswordIconColor="#A61C28"

PlaceholderTextColor="#8A98A580"
WarningColor="#ff3333"

LoginButtonTextColor="#1A1C1E"
LoginButtonBackgroundColor="#A61C28"
SystemButtonsIconsColor="#A61C28"
SessionButtonTextColor="#A61C28"
VirtualKeyboardButtonTextColor="#A61C28"

DropdownTextColor="#8A98A5"
DropdownSelectedBackgroundColor="#EAEAEAbf"
DropdownBackgroundColor="#EAEAEA"

HighlightTextColor="#1A1C1E"
HighlightBackgroundColor="#EAEAEAbf"
HighlightBorderColor="#A61C28"

HoverUserIconColor="#8A98A5"
HoverPasswordIconColor="#8A98A5"
HoverSystemButtonsIconsColor="#8A98A5"
HoverSessionButtonTextColor="#8A98A5"
HoverVirtualKeyboardButtonTextColor="#8A98A5"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
