[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Playfair Display"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Autumn Fire"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/rocks-glow-with-autumn-fire.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#1f0f00"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#ff6600"
AccentGlowColor="#ff6600"

HeaderTextColor="#ff6600"
DateTextColor="#ff6600"
TimeTextColor="#ff6600"

FormBackgroundColor="#1f0f00"
BackgroundColor="#1f0f00"

LoginFieldBackgroundColor="#3d1e00"
PasswordFieldBackgroundColor="#3d1e00"
LoginFieldTextColor="#ffd6b3"
PasswordFieldTextColor="#ffd6b3"
UserIconColor="#ff6600"
PasswordIconColor="#ff6600"

PlaceholderTextColor="#ffd6b380"
WarningColor="#ff3333"

LoginButtonTextColor="#1f0f00"
LoginButtonBackgroundColor="#ff6600"
SystemButtonsIconsColor="#ff6600"
SessionButtonTextColor="#ff6600"
VirtualKeyboardButtonTextColor="#ff6600"

DropdownTextColor="#ffd6b3"
DropdownSelectedBackgroundColor="#3d1e00bf"
DropdownBackgroundColor="#3d1e00"

HighlightTextColor="#1f0f00"
HighlightBackgroundColor="#3d1e00bf"
HighlightBorderColor="#ff6600"

HoverUserIconColor="#ffd6b3"
HoverPasswordIconColor="#ffd6b3"
HoverSystemButtonsIconsColor="#ffd6b3"
HoverSessionButtonTextColor="#ffd6b3"
HoverVirtualKeyboardButtonTextColor="#ffd6b3"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
