[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Ujiro-drJJl"
FontFile="Ujiro-drJJl.otf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Samurai Spirit"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/samurai-spirit-under-the-moon.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#000000"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

# Accent for particle shimmer + avatar glow
AccentParticleColor="#F8F9FA"
AccentGlowColor="#F8F9FA"

HeaderTextColor="#F8F9FA"
DateTextColor="#F8F9FA"
TimeTextColor="#F8F9FA"

FormBackgroundColor="#000000"
BackgroundColor="#000000"

LoginFieldBackgroundColor="#333333"
PasswordFieldBackgroundColor="#333333"
LoginFieldTextColor="#FFB7C5"
PasswordFieldTextColor="#FFB7C5"
UserIconColor="#F8F9FA"
PasswordIconColor="#F8F9FA"

PlaceholderTextColor="#FFB7C580"
WarningColor="#ff6b35"

LoginButtonTextColor="#000000"
LoginButtonBackgroundColor="#F8F9FA"
SystemButtonsIconsColor="#F8F9FA"
SessionButtonTextColor="#F8F9FA"
VirtualKeyboardButtonTextColor="#F8F9FA"

DropdownTextColor="#FFB7C5"
DropdownSelectedBackgroundColor="#333333bf"
DropdownBackgroundColor="#333333"

HighlightTextColor="#000000"
HighlightBackgroundColor="#333333bf"
HighlightBorderColor="#F8F9FA"

HoverUserIconColor="#FFB7C5"
HoverPasswordIconColor="#FFB7C5"
HoverSystemButtonsIconsColor="#FFB7C5"
HoverSessionButtonTextColor="#FFB7C5"
HoverVirtualKeyboardButtonTextColor="#FFB7C5"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection="Session"
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
