[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Ujiro-drJJl"
FontFile="Ujiro-drJJl.otf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Serenity"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/serenity.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#0A0F1E"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#00E5FF"
AccentGlowColor="#00E5FF"

HeaderTextColor="#00E5FF"
DateTextColor="#00E5FF"
TimeTextColor="#00E5FF"

FormBackgroundColor="#0A0F1E"
BackgroundColor="#0A0F1E"

LoginFieldBackgroundColor="#E0FBFC"
PasswordFieldBackgroundColor="#E0FBFC"
LoginFieldTextColor="#F8A5C2"
PasswordFieldTextColor="#F8A5C2"
UserIconColor="#00E5FF"
PasswordIconColor="#00E5FF"

PlaceholderTextColor="#F8A5C280"
WarningColor="#ff3333"

LoginButtonTextColor="#0A0F1E"
LoginButtonBackgroundColor="#00E5FF"
SystemButtonsIconsColor="#00E5FF"
SessionButtonTextColor="#00E5FF"
VirtualKeyboardButtonTextColor="#00E5FF"

DropdownTextColor="#F8A5C2"
DropdownSelectedBackgroundColor="#E0FBFCbf"
DropdownBackgroundColor="#E0FBFC"

HighlightTextColor="#0A0F1E"
HighlightBackgroundColor="#E0FBFCbf"
HighlightBorderColor="#00E5FF"

HoverUserIconColor="#F8A5C2"
HoverPasswordIconColor="#F8A5C2"
HoverSystemButtonsIconsColor="#F8A5C2"
HoverSessionButtonTextColor="#F8A5C2"
HoverVirtualKeyboardButtonTextColor="#F8A5C2"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
