[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Pixel Operator"
FontFile="PixelOperator.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Serenity"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/serenity.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#1a0a12"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#ff99cc"
AccentGlowColor="#ff99cc"

HeaderTextColor="#ff99cc"
DateTextColor="#ff99cc"
TimeTextColor="#ff99cc"

FormBackgroundColor="#1a0a12"
BackgroundColor="#1a0a12"

LoginFieldBackgroundColor="#331424"
PasswordFieldBackgroundColor="#331424"
LoginFieldTextColor="#ffe6f2"
PasswordFieldTextColor="#ffe6f2"
UserIconColor="#ff99cc"
PasswordIconColor="#ff99cc"

PlaceholderTextColor="#ffe6f280"
WarningColor="#ff3333"

LoginButtonTextColor="#1a0a12"
LoginButtonBackgroundColor="#ff99cc"
SystemButtonsIconsColor="#ff99cc"
SessionButtonTextColor="#ff99cc"
VirtualKeyboardButtonTextColor="#ff99cc"

DropdownTextColor="#ffe6f2"
DropdownSelectedBackgroundColor="#331424bf"
DropdownBackgroundColor="#331424"

HighlightTextColor="#1a0a12"
HighlightBackgroundColor="#331424bf"
HighlightBorderColor="#ff99cc"

HoverUserIconColor="#ffe6f2"
HoverPasswordIconColor="#ffe6f2"
HoverSystemButtonsIconsColor="#ffe6f2"
HoverSessionButtonTextColor="#ffe6f2"
HoverVirtualKeyboardButtonTextColor="#ffe6f2"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
