[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Ujiro-drJJl"
FontFile="Ujiro-drJJl.otf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Shadowblade Wanderer"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/shadowblade-wanderer.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#121212"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#B21818"
AccentGlowColor="#B21818"

HeaderTextColor="#B21818"
DateTextColor="#B21818"
TimeTextColor="#B21818"

FormBackgroundColor="#121212"
BackgroundColor="#121212"

LoginFieldBackgroundColor="#D1D1D1"
PasswordFieldBackgroundColor="#D1D1D1"
LoginFieldTextColor="#4A4E52"
PasswordFieldTextColor="#4A4E52"
UserIconColor="#B21818"
PasswordIconColor="#B21818"

PlaceholderTextColor="#4A4E5280"
WarningColor="#ff3333"

LoginButtonTextColor="#121212"
LoginButtonBackgroundColor="#B21818"
SystemButtonsIconsColor="#B21818"
SessionButtonTextColor="#B21818"
VirtualKeyboardButtonTextColor="#B21818"

DropdownTextColor="#4A4E52"
DropdownSelectedBackgroundColor="#D1D1D1bf"
DropdownBackgroundColor="#D1D1D1"

HighlightTextColor="#121212"
HighlightBackgroundColor="#D1D1D1bf"
HighlightBorderColor="#B21818"

HoverUserIconColor="#4A4E52"
HoverPasswordIconColor="#4A4E52"
HoverSystemButtonsIconsColor="#4A4E52"
HoverSessionButtonTextColor="#4A4E52"
HoverVirtualKeyboardButtonTextColor="#4A4E52"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="right"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
