[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Silkscreen"
FontFile="Silkscreen-Regular.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Shadowblade Wanderer"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/shadowblade-wanderer.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#000000"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#808080"
AccentGlowColor="#808080"

HeaderTextColor="#808080"
DateTextColor="#808080"
TimeTextColor="#808080"

FormBackgroundColor="#000000"
BackgroundColor="#000000"

LoginFieldBackgroundColor="#1a1a1a"
PasswordFieldBackgroundColor="#1a1a1a"
LoginFieldTextColor="#e6e6e6"
PasswordFieldTextColor="#e6e6e6"
UserIconColor="#808080"
PasswordIconColor="#808080"

PlaceholderTextColor="#e6e6e680"
WarningColor="#ff3333"

LoginButtonTextColor="#000000"
LoginButtonBackgroundColor="#808080"
SystemButtonsIconsColor="#808080"
SessionButtonTextColor="#808080"
VirtualKeyboardButtonTextColor="#808080"

DropdownTextColor="#e6e6e6"
DropdownSelectedBackgroundColor="#1a1a1abf"
DropdownBackgroundColor="#1a1a1a"

HighlightTextColor="#000000"
HighlightBackgroundColor="#1a1a1abf"
HighlightBorderColor="#808080"

HoverUserIconColor="#e6e6e6"
HoverPasswordIconColor="#e6e6e6"
HoverSystemButtonsIconsColor="#e6e6e6"
HoverSessionButtonTextColor="#e6e6e6"
HoverVirtualKeyboardButtonTextColor="#e6e6e6"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
