[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="PixelOperator"
FontFile="PixelOperator.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Sunset Train"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/anime-train-at-sunset.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#3E206D"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

# Accent for particle shimmer + avatar glow
AccentParticleColor="#FF9E00"
AccentGlowColor="#FF9E00"

HeaderTextColor="#FF9E00"
DateTextColor="#FF9E00"
TimeTextColor="#FF9E00"

FormBackgroundColor="#3E206D"
BackgroundColor="#3E206D"

LoginFieldBackgroundColor="#24142C"
PasswordFieldBackgroundColor="#24142C"
LoginFieldTextColor="#FFD07B"
PasswordFieldTextColor="#FFD07B"
UserIconColor="#FF9E00"
PasswordIconColor="#FF9E00"

PlaceholderTextColor="#FFD07B80"
WarningColor="#ff6b35"

LoginButtonTextColor="#3E206D"
LoginButtonBackgroundColor="#FF9E00"
SystemButtonsIconsColor="#FF9E00"
SessionButtonTextColor="#FF9E00"
VirtualKeyboardButtonTextColor="#FF9E00"

DropdownTextColor="#FFD07B"
DropdownSelectedBackgroundColor="#24142Cbf"
DropdownBackgroundColor="#24142C"

HighlightTextColor="#3E206D"
HighlightBackgroundColor="#24142Cbf"
HighlightBorderColor="#FF9E00"

HoverUserIconColor="#FFD07B"
HoverPasswordIconColor="#FFD07B"
HoverSystemButtonsIconsColor="#FFD07B"
HoverSessionButtonTextColor="#FFD07B"
HoverVirtualKeyboardButtonTextColor="#FFD07B"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection="Session"
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
