[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Pixel Operator"
FontFile="PixelOperator.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Sakura Shrineden"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/yae-miko-among-the-sakura.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#1a0a14"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#ff66b3"
AccentGlowColor="#ff66b3"

HeaderTextColor="#ff66b3"
DateTextColor="#ff66b3"
TimeTextColor="#ff66b3"

FormBackgroundColor="#1a0a14"
BackgroundColor="#1a0a14"

LoginFieldBackgroundColor="#331429"
PasswordFieldBackgroundColor="#331429"
LoginFieldTextColor="#ffd6eb"
PasswordFieldTextColor="#ffd6eb"
UserIconColor="#ff66b3"
PasswordIconColor="#ff66b3"

PlaceholderTextColor="#ffd6eb80"
WarningColor="#ff3333"

LoginButtonTextColor="#1a0a14"
LoginButtonBackgroundColor="#ff66b3"
SystemButtonsIconsColor="#ff66b3"
SessionButtonTextColor="#ff66b3"
VirtualKeyboardButtonTextColor="#ff66b3"

DropdownTextColor="#ffd6eb"
DropdownSelectedBackgroundColor="#331429bf"
DropdownBackgroundColor="#331429"

HighlightTextColor="#1a0a14"
HighlightBackgroundColor="#331429bf"
HighlightBorderColor="#ff66b3"

HoverUserIconColor="#ffd6eb"
HoverPasswordIconColor="#ffd6eb"
HoverSystemButtonsIconsColor="#ffd6eb"
HoverSessionButtonTextColor="#ffd6eb"
HoverVirtualKeyboardButtonTextColor="#ffd6eb"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
