[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Ming_Imperial_600"
FontFile="Ming_Imperial_600.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Sakura Shrineden"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/yae-miko-among-the-sakura.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#4A1E30"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#F8C8DC"
AccentGlowColor="#F8C8DC"

HeaderTextColor="#F8C8DC"
DateTextColor="#F8C8DC"
TimeTextColor="#F8C8DC"

FormBackgroundColor="#4A1E30"
BackgroundColor="#4A1E30"

LoginFieldBackgroundColor="#D291BC"
PasswordFieldBackgroundColor="#D291BC"
LoginFieldTextColor="#FFF9F0"
PasswordFieldTextColor="#FFF9F0"
UserIconColor="#F8C8DC"
PasswordIconColor="#F8C8DC"

PlaceholderTextColor="#FFF9F080"
WarningColor="#ff3333"

LoginButtonTextColor="#4A1E30"
LoginButtonBackgroundColor="#F8C8DC"
SystemButtonsIconsColor="#F8C8DC"
SessionButtonTextColor="#F8C8DC"
VirtualKeyboardButtonTextColor="#F8C8DC"

DropdownTextColor="#FFF9F0"
DropdownSelectedBackgroundColor="#D291BCbf"
DropdownBackgroundColor="#D291BC"

HighlightTextColor="#4A1E30"
HighlightBackgroundColor="#D291BCbf"
HighlightBorderColor="#F8C8DC"

HoverUserIconColor="#FFF9F0"
HoverPasswordIconColor="#FFF9F0"
HoverSystemButtonsIconsColor="#FFF9F0"
HoverSessionButtonTextColor="#FFF9F0"
HoverVirtualKeyboardButtonTextColor="#FFF9F0"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
