[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Pixel Operator"
FontFile="PixelOperator.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Mortal's Journey"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/zi-ling-a-mortals-journey-to-immortality.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#051a0f"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#33ff99"
AccentGlowColor="#33ff99"

HeaderTextColor="#33ff99"
DateTextColor="#33ff99"
TimeTextColor="#33ff99"

FormBackgroundColor="#051a0f"
BackgroundColor="#051a0f"

LoginFieldBackgroundColor="#0a331f"
PasswordFieldBackgroundColor="#0a331f"
LoginFieldTextColor="#ccffeb"
PasswordFieldTextColor="#ccffeb"
UserIconColor="#33ff99"
PasswordIconColor="#33ff99"

PlaceholderTextColor="#ccffeb80"
WarningColor="#ff3333"

LoginButtonTextColor="#051a0f"
LoginButtonBackgroundColor="#33ff99"
SystemButtonsIconsColor="#33ff99"
SessionButtonTextColor="#33ff99"
VirtualKeyboardButtonTextColor="#33ff99"

DropdownTextColor="#ccffeb"
DropdownSelectedBackgroundColor="#0a331fbf"
DropdownBackgroundColor="#0a331f"

HighlightTextColor="#051a0f"
HighlightBackgroundColor="#0a331fbf"
HighlightBorderColor="#33ff99"

HoverUserIconColor="#ccffeb"
HoverPasswordIconColor="#ccffeb"
HoverSystemButtonsIconsColor="#ccffeb"
HoverSessionButtonTextColor="#ccffeb"
HoverVirtualKeyboardButtonTextColor="#ccffeb"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
