[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Ming_Imperial_600"
FontFile="Ming_Imperial_600.ttf"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText="Mortal's Journey"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/zi-ling-a-mortals-journey-to-immortality.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.15"
DimBackgroundColor="#F8F4E3"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

AccentParticleColor="#D4AF37"
AccentGlowColor="#D4AF37"

HeaderTextColor="#D4AF37"
DateTextColor="#D4AF37"
TimeTextColor="#D4AF37"

FormBackgroundColor="#F8F4E3"
BackgroundColor="#F8F4E3"

LoginFieldBackgroundColor="#8E94B5"
PasswordFieldBackgroundColor="#8E94B5"
LoginFieldTextColor="#2B2129"
PasswordFieldTextColor="#2B2129"
UserIconColor="#D4AF37"
PasswordIconColor="#D4AF37"

PlaceholderTextColor="#2B212980"
WarningColor="#ff3333"

LoginButtonTextColor="#F8F4E3"
LoginButtonBackgroundColor="#D4AF37"
SystemButtonsIconsColor="#D4AF37"
SessionButtonTextColor="#D4AF37"
VirtualKeyboardButtonTextColor="#D4AF37"

DropdownTextColor="#2B2129"
DropdownSelectedBackgroundColor="#8E94B5bf"
DropdownBackgroundColor="#8E94B5"

HighlightTextColor="#F8F4E3"
HighlightBackgroundColor="#8E94B5bf"
HighlightBorderColor="#D4AF37"

HoverUserIconColor="#2B2129"
HoverPasswordIconColor="#2B2129"
HoverSystemButtonsIconsColor="#2B2129"
HoverSessionButtonTextColor="#2B2129"
HoverVirtualKeyboardButtonTextColor="#2B2129"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.5"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
